name: Daily protocol updates
on:
  workflow_dispatch: { } # to allow manual trigger
  schedule:
    # Every night at 4am
    - cron: "0 4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Update protocol
        uses: burrunan/gradle-cache-action@v1
        with:
          # jobs with different JDK versions can't share caches
          job-id: jdk11
          arguments: updateProtocolDefinitions

      - name: Read protocol version
        uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: protocol/version.txt
          trim: true

      - name: Update public ABI descriptors
        uses: burrunan/gradle-cache-action@v1
        with:
          # jobs with different JDK versions can't share caches
          job-id: jdk11
          # We already deal with caches in a previous gradle-cache-action
          execution-only-caches: true
          arguments: apiDump

      - name: Create pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "protocol-update"
          author: "Protocol Update Workflow <protocol-updater@users.noreply.github.com>"
          committer: "Protocol Update Workflow <protocol-updater@users.noreply.github.com>"
          commit-message: "Update to Chrome DevTools Protocol version ${{ steps.version.outputs.text }}"
          title: "Update to Chrome DevTools Protocol version ${{ steps.version.outputs.text }}"
          body: |
            This PR updates the protocol definitions (under `protocol/`) to the latest version found in
            [the `devtools-protocol` github repo](https://github.com/ChromeDevTools/devtools-protocol/tree/master/json).

            The ABI descriptors (under `api/`) are also updated to reflect the changes in the generated code.
