name: Daily protocol updates
on:
  workflow_dispatch: { } # to allow manual trigger
  schedule:
    # Every night at 4am
    - cron: "0 4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Update protocol
        uses: gradle/gradle-build-action@v2
        with:
          arguments: updateProtocolDefinitions

      - name: Read protocol version
        id: protocol-version
        run: echo "version=$(cat protocol-definition/version.txt)" >> $GITHUB_OUTPUT

      - name: Update public ABI descriptors
        uses: gradle/gradle-build-action@v2
        with:
          arguments: apiDump

      - name: Create pull-request
        uses: peter-evans/create-pull-request@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # using personal token to trigger CI build
        with:
          branch: "protocol-update"
          author: "Protocol Update Workflow <protocol-updater@users.noreply.github.com>"
          committer: "Protocol Update Workflow <protocol-updater@users.noreply.github.com>"
          commit-message: "Update to Chrome DevTools Protocol version ${{ steps.protocol-version.outputs.version }}"
          title: "Update to Chrome DevTools Protocol version ${{ steps.protocol-version.outputs.version }}"
          labels: dependencies
          body: |
            This PR updates the protocol definitions (under `protocol-definition/`) to the latest version found in
            [the `devtools-protocol` github repo](https://github.com/ChromeDevTools/devtools-protocol/tree/master/json).

            The ABI descriptors (under `api/`) are also updated to reflect the changes in the generated code.
